#!/usr/bin/env bash
# =============================================================================
# bkt Demo Data Seeder
# =============================================================================
# Populates bucket(s) with a spread of file types in a few folders, via the
# REST API (exactly what the UI does), so you can see real data in the bkt UI
# and — for S3-backed buckets — in the AWS console. Nothing is deleted; objects
# are overwritten on re-run, so it's safe to run repeatedly.
#
# Usage:
#   ./tests/seed.sh                          # seed every bucket the admin can see
#   ./tests/seed.sh debug-bucket bkt-demo-7c1e9a
#   ./tests/seed.sh --endpoint https://localhost:9443 --password pass debug-bucket
#
# Requirements: curl, python3
# =============================================================================
set -euo pipefail

BKT_ENDPOINT="${BKT_ENDPOINT:-https://localhost:9443}"
BKT_USERNAME="${BKT_USERNAME:-admin}"
BKT_PASSWORD="${BKT_PASSWORD:-}"
BUCKETS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    --endpoint) BKT_ENDPOINT="$2"; shift 2 ;;
    --username) BKT_USERNAME="$2"; shift 2 ;;
    --password) BKT_PASSWORD="$2"; shift 2 ;;
    -*) echo "Unknown flag: $1"; exit 1 ;;
    *)  BUCKETS+=("$1"); shift ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"
if [[ -z "$BKT_PASSWORD" && -f "$ENV_FILE" ]]; then
  BKT_PASSWORD=$(grep -E '^ADMIN_PASSWORD=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"'"'"'')
fi
[[ -z "$BKT_PASSWORD" ]] && { echo "Error: password required (--password or ADMIN_PASSWORD in .env)"; exit 1; }

GREEN='\033[0;32m'; RED='\033[0;31m'; CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'
api() { curl -sk --max-time 60 "$@"; }

# ── Login ─────────────────────────────────────────────────────────────────────
JWT=$(api -X POST "${BKT_ENDPOINT}/api/auth/login" -H 'Content-Type: application/json' \
  -d "{\"username\":\"${BKT_USERNAME}\",\"password\":\"${BKT_PASSWORD}\"}" \
  | grep -o '"token":"[^"]*"' | cut -d'"' -f4)
[[ -z "$JWT" ]] && { echo "Error: login failed"; exit 1; }

# ── Resolve target buckets (args, or all visible) ─────────────────────────────
if [[ ${#BUCKETS[@]} -eq 0 ]]; then
  mapfile -t BUCKETS < <(api "${BKT_ENDPOINT}/api/buckets" -H "Authorization: Bearer ${JWT}" \
    | python3 -c "import sys,json; [print(b['name']) for b in json.load(sys.stdin)]")
fi
[[ ${#BUCKETS[@]} -eq 0 ]] && { echo "No buckets to seed."; exit 0; }

# ── File generators (small, dependency-free) ──────────────────────────────────
WORK=$(mktemp -d "${TMPDIR:-/tmp}/bkt-seed-XXXXXX")
trap 'rm -rf "$WORK"' EXIT

gen_files() {
  printf 'bkt demo — plain text\nseeded %s\n' "$(date)"            > "$WORK/notes.txt"
  printf '{"demo":true,"source":"bkt-seed","ts":"%s"}\n' "$(date -u +%FT%TZ)" > "$WORK/data.json"
  printf 'id,name,value\n1,alpha,100\n2,beta,200\n3,gamma,300\n'   > "$WORK/records.csv"
  printf '# bkt demo\n\nA **markdown** file seeded for testing.\n' > "$WORK/readme.md"
  printf '<html><body><h1>bkt demo</h1><p>seeded</p></body></html>' > "$WORK/page.html"
  printf '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><rect width="16" height="16" fill="#3b82f6"/></svg>' > "$WORK/icon.svg"
  # PNG (1x1), JPEG (1x1), GIF (1x1), minimal PDF — generated by python3
  python3 - "$WORK" <<'PY'
import struct, zlib, sys, os
d = sys.argv[1]
def chunk(t, data): return struct.pack('>I', len(data)) + t + data + struct.pack('>I', zlib.crc32(t+data)&0xffffffff)
png = b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB',1,1,8,2,0,0,0)) + chunk(b'IDAT', zlib.compress(b'\x00\xff\xff\xff')) + chunk(b'IEND', b'')
open(os.path.join(d,'pixel.png'),'wb').write(png)
jpg = bytes([0xFF,0xD8,0xFF,0xE0,0x00,0x10,0x4A,0x46,0x49,0x46,0x00,0x01,0x01,0x00,0x00,0x01,0x00,0x01,0x00,0x00,
  0xFF,0xDB,0x00,0x43,0x00]+[0x08]*64+[0xFF,0xC0,0x00,0x0B,0x08,0x00,0x01,0x00,0x01,0x01,0x01,0x11,0x00,
  0xFF,0xC4,0x00,0x1F,0x00]+[0x00]*28+[0xFF,0xDA,0x00,0x08,0x01,0x01,0x00,0x00,0x3F,0x00,0xFB,0xFF,0xD9])
open(os.path.join(d,'photo.jpg'),'wb').write(jpg)
gif = b'GIF89a\x01\x00\x01\x00\x00\x00\x00!\xf9\x04\x00\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;'
open(os.path.join(d,'anim.gif'),'wb').write(gif)
pdf = b'%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n3 0 obj<</Type/Page/MediaBox[0 0 3 3]>>endobj\ntrailer<</Size 4/Root 1 0 R>>\n%%EOF'
open(os.path.join(d,'report.pdf'),'wb').write(pdf)
PY
  head -c 16384 /dev/urandom > "$WORK/random.bin"
}

# bucket, local-file, destination-key
upload() {
  local bucket="$1" file="$2" key="$3" code
  code=$(api -X POST "${BKT_ENDPOINT}/api/buckets/${bucket}/objects" \
    -H "Authorization: Bearer ${JWT}" \
    -F "file=@${file}" -F "key=${key}" -w "%{http_code}" -o /dev/null)
  if [[ "$code" == "200" || "$code" == "201" ]]; then
    echo -e "    ${GREEN}✔${RESET} ${key}"
  else
    echo -e "    ${RED}✖${RESET} ${key} (HTTP ${code})"
  fi
}

gen_files

echo -e "${BOLD}Seeding ${#BUCKETS[@]} bucket(s) at ${BKT_ENDPOINT}${RESET}"
for bucket in "${BUCKETS[@]}"; do
  backend=$(api "${BKT_ENDPOINT}/api/buckets/${bucket}" -H "Authorization: Bearer ${JWT}" \
    | python3 -c "import sys,json; print(json.load(sys.stdin).get('storage_backend','?'))" 2>/dev/null || echo "?")
  echo -e "\n${BOLD}── ${bucket} ${CYAN}(${backend})${RESET}${BOLD} ──${RESET}"
  upload "$bucket" "$WORK/notes.txt"   "documents/notes.txt"
  upload "$bucket" "$WORK/readme.md"   "documents/readme.md"
  upload "$bucket" "$WORK/report.pdf"  "documents/report.pdf"
  upload "$bucket" "$WORK/data.json"   "data/data.json"
  upload "$bucket" "$WORK/records.csv" "data/records.csv"
  upload "$bucket" "$WORK/random.bin"  "data/random.bin"
  upload "$bucket" "$WORK/pixel.png"   "images/pixel.png"
  upload "$bucket" "$WORK/photo.jpg"   "images/photo.jpg"
  upload "$bucket" "$WORK/anim.gif"    "images/anim.gif"
  upload "$bucket" "$WORK/icon.svg"    "images/icon.svg"
  upload "$bucket" "$WORK/page.html"   "web/page.html"
done

echo -e "\n${GREEN}${BOLD}Done.${RESET} View in the UI, or for S3 buckets check the AWS console."
