{{- if and .Values.ingress.enabled .Values.ingress.s3.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bkt.fullname" . }}-s3
  labels:
    {{- include "bkt.labels" . | nindent 4 }}
  {{- with .Values.ingress.s3.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.s3.tls }}
  tls:
    {{- toYaml .Values.ingress.s3.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.s3.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "bkt.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.s3Port }}
{{- end }}
