{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bkt.fullname" . }}
  labels:
    {{- include "bkt.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bkt.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
    - port: https
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.backend.tls.enabled }}
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      {{- end }}
      {{- with .Values.serviceMonitor.bearerTokenSecret }}
      bearerTokenSecret:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
